### ISSUE TITLE
[Feature] VS Code integration: Aptos, Solidity local 

### ISSUE THREAD

**Issue by hien-p** [Weminal-labs/Movelazy#6]
cc: @Menh1505  @Khoa-Dam @Huc06

**Comment by Menh1505** [comment]
- Sol/Hardhat interact
- [x] Config
- [x] **check**                 Check whatever you need
- [x] **clean**                 Clears the cache and deletes all artifacts
- [x]  ⏫**compile**              Compiles the entire project, building all artifacts
- [x] **console**               Opens a hardhat console
- [x] **coverage**              Generates a code coverage report for tests
- [x] **flatten**               Flattens and prints contracts and their dependencies
- [x] **help**                  Prints this message
- [x] **node**                  Starts a JSON-RPC server on top of Hardhat Network
- [x] ⏫ **run**                   Runs a user-defined script after compiling the project
- [x] ⏫ **test**                  Runs mocha tests
- [x] **typechain**             Generate Typechain typings for compiled contracts
- [ ] **verify**                Verifies contract on Etherscan

**Comment by hien-p** [comment]
Good I will close this
